package riftyboi.cbcmodernwarfare.munitions.munitions_contraption_launcher.config;

import rbasamoyai.createbigcannons.munitions.config.components.BallisticPropertiesComponent;
import rbasamoyai.createbigcannons.munitions.config.components.EntityDamagePropertiesComponent;
import riftyboi.cbcmodernwarfare.munitions.munitions_contraption_launcher.config.components.FuelTankPropertiesComponent;
import riftyboi.cbcmodernwarfare.munitions.munitions_contraption_launcher.config.components.GuidanceBlockPropertiesComponent;

public record GuidanceBlockProperties(GuidanceBlockPropertiesComponent guidanceBlockProperties, BallisticPropertiesComponent ballisticPropertiesComponent, EntityDamagePropertiesComponent entityDamagePropertiesComponent) {
}
