package riftyboi.cbcmodernwarfare.munitions.munitions_contraption_launcher.fuel_tanks;

import riftyboi.cbcmodernwarfare.munitions.munitions_contraption_launcher.FuelType;
import riftyboi.cbcmodernwarfare.munitions.munitions_contraption_launcher.PropelledContraptionMunitionBlock;
import riftyboi.cbcmodernwarfare.munitions.munitions_contraption_launcher.config.FuelTankProperties;

public interface IFuelTankBlock extends PropelledContraptionMunitionBlock {
	FuelTankProperties getProperties();
	FuelType getFuelType();
}
